# Generated by Django 3.2.4 on 2021-06-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain_games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(db_index=True, max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='name',
            name='name',
        ),
    ]
