# Generated by Django 3.2.4 on 2021-07-01 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brain_games', '0002_auto_20210629_2018'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='name',
            new_name='User',
        ),
    ]
